; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_qtpy_esp32]
platform = espressif32
board = adafruit_qtpy_esp32
board_build.partitions = era_partition.csv
framework = arduino
lib_deps = 
	protocentral/ProtoCentral MAX30001@^2.0.0
	https://github.com/MakerLabLPI/Max86141.git
	eoh-ltd/ERa@^1.6.4
